version: "3"
services: 
    nginx:
        build: ./nginx
        links: 
            - AUTH:AUTH
           
        ports:
            - "80:80"
        networks: 
            - E-commerce-API-Micro-Services
    
    AUTH:
        # restart: always
        build: ./AUTH
        volumes: 
            - /AUTH/node_modules
            - ./AUTH:/app
        ports:
            - 5000:5000
        links: 
            - db
        depends_on: 
            - db
        environment: 
            PORT: 5000
            NODE_ENV: production
           
        networks: 
            - E-commerce-API-Micro-Services

    
    


    db:
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=E-Commerce-Api
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=mysecretpassword
        ports:
            - "5432:5432"
        restart: unless-stopped

        networks: 
            - E-commerce-API-Micro-Services
  
networks: 
    E-commerce-API-Micro-Services:
        driver: bridge

volumes: 
    postgres-data:
        driver: local